services:
  db:
    image: postgres:16.3
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres_data:
