name: Fork Sync

on:
  schedule:
    - cron: '0 12 * * *' # 毎日 12:00pm
  workflow_dispatch: # 手作業での実行も可

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tgymnich/fork-sync@v2
        with:
          head: main # form 元リポジトリのブランチ
          base: main # fork 先リポジトリ (== ワークフローが動作するリポジトリ) の PR マージ対象ブランチ
          token: ${{ secrets.GITHUB_TOKEN }}
          auto_approve: false # 自動 Approve しない
          auto_merge: false # 自動 merge しない
