name: test
on: [push]

jobs:
  model:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U app_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:password@127.0.0.1:5432/app_test?schema=public
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
          cache: 'pnpm'

      - name: Waitting for PostgreSQL
        run: |
          echo "Waitting for PostgreSQL to be ready..."

      - run: pnpm install

      - run: pnpm --filter @repo/model db:generate

      - run: pnpm --filter @repo/model db:migrate

      - run: pnpm --filter @repo/model test
