name: Validate renovate.json

on:
  push:
    branches:
      - main
    paths:
      - renovate.json
  pull_request:
    branches:
      - main
    paths:
      - renovate.json

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Validate renovate.json
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: renovate.json
